version: 0.2

phases:
  install:
    commands:
      - echo Installing RSpec...
      - gem install rspec
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Ruby code...
      - rspec --format documentation HelloWorld_spec.rb  | tee output.log
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - output.log

